### ISSUE TITLE
File paths with spaces will cause this package to error out.

### ISSUE THREAD

**Issue by MattFoley** [fdnhkj/react-native-shared-code#2]
Working on a fix now. (Also note that it looks like Node 6.x is required?)

**Comment by MattFoley** [comment]
Not having a lot of luck here. The gist is just that fs doesn't want to handle spaces in paths properly.

**Comment by MattFoley** [comment]
Here's a PR to fix this: https://github.com/fdnhkj/react-native-shared-code/pull/3

**Comment by fdnhkj** [comment]
Fixed in #3
